### ISSUE TITLE
utf-8 character encoding

### ISSUE THREAD

**Issue by Mus1c** [MMMZZZZ/Nextion2Text#14]
I have a project with utf-8 character encoding, because this is the only way to get Chinese characters working.
For example, I have a text element with the following txt string:
Gerät Code|Code|Code|Codice|Código|Kod|代码

Using Nextion2Text.py, I get the following output in the cmd window:

Traceback (most recent call last):
  File "D:\Projekte\NextionTest\Nextion2Text.py", line 1851, in <module>
    f.write(text)
  File "C:\Program Files\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\x81' in position 5744: character maps to <undefined>

I would greatly appreciate any help. Thanks!

**Comment by Mus1c** [comment]
I use the character set 115: CJK Unified Ideographs

**Comment by Mus1c** [comment]
I have solved this issue by adding
`encoding="utf-8"`
into all open() function calls
[see stackoverflow question](https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters)
example:
`open(***, "w", encoding="utf-8")`

I have attached the updated script, please check and commit, thanks
[Nextion2Text.zip](https://github.com/MMMZZZZ/Nextion2Text/files/12408535/Nextion2Text.zip)

**Comment by edwardtfn** [comment]
This solution worked fine for me so far.
Why don´t you create a PR and propose the change to the repo?

**Comment by Mus1c** [comment]
Hi, thanks for testing. I'm not practiced enough, never done a commit on github before

**Comment by edwardtfn** [comment]
There's always a first time. :)

As it is your first commit, I believe you don't have GitHub Desktop installed, so I will add here a short step-by-step to do it directly on the web interface:

1. Copy the content of your modified file<br><br>
2. Open the file in the repository and click the edit button to start a fork:<br>![image](https://github.com/MMMZZZZ/Nextion2Text/assets/94725493/f3993ef6-11fd-4234-9cdb-bfe4664566e1)<br><br>
3. Click "Fork this repository"<br><br>
4. Select all the text/code there and replace by the one you copied from your local modified code. If you click the "Preview" button, you will be able to see the lines you changed highlighted. This is a good check-point.<br>
![image](https://github.com/MMMZZZZ/Nextion2Text/assets/94725493/65862e6c-7775-475d-9a1c-1925cf22e93b)<br><br>
5. Click "Commit changes..."<br>
![image](https://github.com/MMMZZZZ/Nextion2Text/assets/94725493/c160b518-a13f-4173-9144-e1b828d4a96f)<br><br>
6. Add a title and a short description for your commit and then click "Propose changes".<br>
![image](https://github.com/MMMZZZZ/Nextion2Text/assets/94725493/28e51b41-a0f8-4088-870f-90ac439474fc)<br><br>
7. You will get to the "Pull request" flow, where you can check your changes again (or add something you might be missing). Click "Create pull request" if everything looks right.<br><br>
8. Review the title and description for your pull request and then click "Create pull request"<br><br>
9. You are done! 😃

**Comment by Mus1c** [comment]
> There's always a first time. :)
> 
> As it is your first commit, I believe you don't have GitHub Desktop installed, so I will add here a short step-by-step to do it directly on the web interface:

Thank you very much, it is really easy if you know the procedure! I have created the pull request and I will close the Issue.
