### ISSUE TITLE
Problem with nextion2text

### ISSUE THREAD

**Issue by kang2k10** [MMMZZZZ/Nextion2Text#9]
Traceback (most recent call last):
  File "D:\Nextion2Text.py", line 1791, in <module>
    text = page.getText(emptyLinesLimit=1, includeUnknown=includeUnknown,
  File "D:\Nextion2Text.py", line 1550, in getText
    return "".join(self.getTextLines(*args, **kwargs))
  File "D:\Nextion2Text.py", line 1542, in getTextLines
    comps = sorted(self.components, key=key)
  File "D:\Nextion2Text.py", line 1508, in <lambda>
    defaultTextSort = lambda c: Page._defaultSortList.index(c.rawData["att"]["type"])
ValueError: 5 is not in list

**Comment by kang2k10** [comment]
How to fix it?

**Comment by MMMZZZZ** [comment]
Hi @kang2k10,

I'm currently quite busy with other projects so I can't give you any estimate. I'd assume this is the new TouchCap component but I don't know (as I said, currently don't have the time to look into this). If so, just add it to this dictionary: 
https://github.com/MMMZZZZ/Nextion2Text/blob/master/Nextion2Text.py#L70
If you don't know whether it's the TouchCap or not you can also add it as "Unknown". The important thing is that the 5 needs to be a key in that dictionary. 

Regards,
Max

**Comment by kang2k10** [comment]
Verry thanks!
i add after 51:  "Timer",
5: "TouchCap",
and all work.
